<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Agora</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
    <PackageReference Include="Supabase" Version="1.1.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="AgoraASMShield\**" />
    <Content Remove="AgoraASMShield\**" />
    <EmbeddedResource Remove="AgoraASMShield\**" />
    <None Remove="AgoraASMShield\**" />
  </ItemGroup>
  <ItemGroup>
    <!-- Copiar la DLL principal de C++ a la raíz -->
    <Content Include="x64\$(Configuration)\AgoraASMShield.dll">
      <Link>AgoraASMShield.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!-- En modo Debug, copiar las DLLs de depuración de vcpkg (OpenSSL, Azure, etc.) -->
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <Content Include="AgoraASMShield\vcpkg_installed\x64-windows\debug\bin\*.dll">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <!-- Dependencia TPM -->
    <Content Include="AgoraASMShield\tss-msr\TSS.CPP\bin\x64\Debug\TSS.CPP.dll">
      <Link>TSS.CPP.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!-- En modo Release, copiar las DLLs de producción de vcpkg -->
  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <Content Include="AgoraASMShield\vcpkg_installed\x64-windows\bin\*.dll">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <!-- Dependencia TPM -->
    <Content Include="AgoraASMShield\tss-msr\TSS.CPP\bin\x64\Release\TSS.CPP.dll">
      <Link>TSS.CPP.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Remove="Components\PostCard.xaml" />
    <None Remove="Components\Post\MediaGrid.xaml" />
    <None Remove="Views\Login\Login.xaml" />
    <None Remove="Views\Main\Feed\Following.xaml" />
    <None Remove="Views\Main\Feed\ForYouPage.xaml" />
    <None Remove="Views\Main\Home.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\Main\Feed\Following.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\Main\Feed\Following.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\Main\Home.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\Login\Login.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\Main\Feed\ForYouPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Components\PostCard.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Components\Post\MediaGrid.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
	
  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <DefaultLanguage>es-ES</DefaultLanguage>
    <PackageCertificateThumbprint>DA69E1F2A7742D41AA2B431931C832B137DCA1C2</PackageCertificateThumbprint>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
  </PropertyGroup>
</Project>